USE DATABASE Prd_QA_DB2;
CREATE SCHEMA QA_DB2_Sc1;
CREATE TABLE QA_1
(
   FIRST_NAME VARCHAR, 
   LAST_NAME VARCHAR, 
   AGE NUMBER

);

INSERT INTO QA_1
VALUES ('MS', 'DHONI', 42), ('Rahul', 'Dravid', 52), ('Virat', 'Kholi', 38)
;